version: "3.9"

volumes:
  mysql_data:

services:
  node:
    depends_on:
      - mysql
      - redis
    build:
      context: .
      network: host
    ports:
      - "8000:8000"
    volumes: # for public stuff
      - .:/code
    env_file:
     vars.env
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  mysql:
    image: "mysql"
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      vars.env
